baseURL: "//www.bozaro.ru/"
languageCode: "ru-ru"
title: "Bozaro. Экспериментариум"
theme: hugo-geo

params:
  title: "Bozaro"
  subtitle: "Artem V. Navrotskiy"  
  blogtitle: "Экспериментариум"

  highlight: true

  # Render the rotating globe in the sidebar
  showglobe: true

  # Google Analytics
  analytics: "UA-8091129-1"
  metrika: 792360

  # Sidebar profile picture
  profilepic: "img/bozaro.png"
  favicon: "img/favicon.png"
  css:
  - "/css/bozaro.css"

  # Social buttons for sidebar
  github: "https://github.com/bozaro"
  twitter: "https://twitter.com/bozaro"
  linkedin: "https://www.linkedin.com/in/bozaro"
  email: "bozaro@yandex.ru"

indexes:
  tag: "tags"

permalinks:
  post: /:year/:month/:day/:slug/

disable404: true
metadataFormat: "yaml"
