BaseURL: "//www.bozaro.ru/"
LanguageCode: "ru-ru"
Title: "Bozaro. Кладезь бредовых мыслей"

Params:
  Author: "Artem V. Navrotskiy"
  DateForm: "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID: "UA-8091129-1"
  Facebook: "bozaro"
  Twitter: "bozaro"
  Github: "bozaro"
  ShowRelatedPost: True
  SyntaxHighlightTheme: "solarized_light.min.css"

Indexes:
  tag: "tags"

permalinks:
  post: /:year/:month/:day/:slug/

MetadataFormat: "yaml"
