baseURL: "https://bozaro.ru/"
languageCode: "ru"
title: "Bozaro. Экспериментариум"
theme: hugo-geo
paginate: 10
enableGitInfo: true
params:
  title: "Bozaro"
  subtitle: "Artem V. Navrotskiy"  
  header: "Экспериментариум"

  # Render the rotating globe in the sidebar
  showglobe: true

  # Google Analytics
  analytics: "UA-8091129-1"
  metrika: 792360

  # Sidebar profile picture
  profilepic: "img/bozaro.jpg"
  favicon: "img/favicon.png"
  css:
  - "/css/bozaro.css"

  # Social buttons for sidebar
  email: "bozaro@yandex.ru"
  socialbuttons:
  - faicon: "twitter"
    url: "https://twitter.com/bozaro"
  - faicon: "linkedin"
    url: "https://linkedin.com/in/bozaro"

  - faicon: "github"
    url: "https://github.com/bozaro"

  navlinks:
  - name: Blog
    url: ""

social:
  twitter: Bozaro

indexes:
  tag: "tags"

permalinks:
  post: /:year/:month/:day/:slug/

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs

relativeURLs: true
disable404: true
metadataFormat: "yaml"
disqusShortname: "http-www-bozaro-ru"
