py_binary(
    name = "stamping",
    srcs = ["stamping.py"],
    python_version = "PY3",
    visibility = ["//visibility:public"],
)

config_setting(
    name = "stamp_detect",
    values = {"stamp": "1"},
    visibility = ["//visibility:public"],
)
